-- ============================================
-- EXERCISE LIBRARY EXPANSION (CA-101)
-- Target: 300+ exercises. Idempotent by name.
-- Run AFTER exercise-library-seed.sql
-- ============================================

INSERT INTO exercises (name, muscle_group, equipment, difficulty)
SELECT * FROM (VALUES
  ('Dumbbell Bench Press', 'Chest', 'Dumbbell', 'beginner'),
  ('Incline Barbell Bench Press', 'Chest', 'Barbell', 'intermediate'),
  ('Decline Dumbbell Press', 'Chest', 'Dumbbell', 'intermediate'),
  ('Floor Press', 'Chest', 'Barbell', 'intermediate'),
  ('Dumbbell Floor Press', 'Chest', 'Dumbbell', 'beginner'),
  ('Machine Chest Press', 'Chest', 'Machine', 'beginner'),
  ('Smith Machine Bench Press', 'Chest', 'Machine', 'beginner'),
  ('Incline Cable Fly', 'Chest', 'Cable', 'intermediate'),
  ('Decline Cable Fly', 'Chest', 'Cable', 'intermediate'),
  ('Pec Deck Fly', 'Chest', 'Machine', 'beginner'),
  ('Svend Press', 'Chest', 'Dumbbell', 'beginner'),
  ('Landmine Press', 'Chest', 'Barbell', 'intermediate'),
  ('Single-Arm Cable Chest Press', 'Chest', 'Cable', 'intermediate'),
  ('Push-Up Wide Grip', 'Chest', 'Bodyweight', 'beginner'),
  ('Diamond Push-Up', 'Chest', 'Bodyweight', 'intermediate'),
  ('Decline Push-Up', 'Chest', 'Bodyweight', 'intermediate'),
  ('Incline Push-Up', 'Chest', 'Bodyweight', 'beginner'),
  ('Archer Push-Up', 'Chest', 'Bodyweight', 'advanced'),
  ('Plyo Push-Up', 'Chest', 'Bodyweight', 'advanced'),
  ('Chest Dip', 'Chest', 'Bodyweight', 'intermediate'),
  ('Ring Push-Up', 'Chest', 'Bodyweight', 'advanced'),
  ('Guillotine Press', 'Chest', 'Barbell', 'advanced'),
  ('Neutral-Grip Dumbbell Press', 'Chest', 'Dumbbell', 'beginner'),
  ('Low Cable Crossover', 'Chest', 'Cable', 'intermediate'),
  ('High Cable Crossover', 'Chest', 'Cable', 'intermediate'),
  ('Machine Incline Press', 'Chest', 'Machine', 'beginner'),
  ('Paused Bench Press', 'Chest', 'Barbell', 'intermediate'),
  ('Spoto Press', 'Chest', 'Barbell', 'advanced'),
  ('Board Press', 'Chest', 'Barbell', 'advanced'),
  ('Hex Press', 'Chest', 'Dumbbell', 'beginner'),
  ('Chin-Up', 'Back', 'Bodyweight', 'intermediate'),
  ('Neutral-Grip Pull-Up', 'Back', 'Bodyweight', 'intermediate'),
  ('Assisted Pull-Up', 'Back', 'Machine', 'beginner'),
  ('Chest-Supported Row', 'Back', 'Dumbbell', 'beginner'),
  ('Pendlay Row', 'Back', 'Barbell', 'advanced'),
  ('Yates Row', 'Back', 'Barbell', 'intermediate'),
  ('Meadows Row', 'Back', 'Barbell', 'advanced'),
  ('Cable Straight-Arm Pullover', 'Back', 'Cable', 'beginner'),
  ('Dumbbell Pullover', 'Back', 'Dumbbell', 'beginner'),
  ('Machine Row', 'Back', 'Machine', 'beginner'),
  ('Inverted Row', 'Back', 'Bodyweight', 'beginner'),
  ('Ring Row', 'Back', 'Bodyweight', 'beginner'),
  ('Seal Row', 'Back', 'Barbell', 'intermediate'),
  ('Kroc Row', 'Back', 'Dumbbell', 'advanced'),
  ('Wide-Grip Lat Pulldown', 'Back', 'Cable', 'beginner'),
  ('Close-Grip Lat Pulldown', 'Back', 'Cable', 'beginner'),
  ('Single-Arm Lat Pulldown', 'Back', 'Cable', 'intermediate'),
  ('Face-Down Incline Row', 'Back', 'Dumbbell', 'beginner'),
  ('Rack Pull', 'Back', 'Barbell', 'intermediate'),
  ('Sumo Deadlift', 'Back', 'Barbell', 'intermediate'),
  ('Trap Bar Deadlift', 'Back', 'Barbell', 'intermediate'),
  ('Snatch-Grip Deadlift', 'Back', 'Barbell', 'advanced'),
  ('Deficit Deadlift', 'Back', 'Barbell', 'advanced'),
  ('Good Morning', 'Back', 'Barbell', 'intermediate'),
  ('Hyperextension', 'Back', 'Machine', 'beginner'),
  ('Reverse Hyperextension', 'Back', 'Machine', 'intermediate'),
  ('Superman Hold', 'Back', 'Bodyweight', 'beginner'),
  ('Bird Dog', 'Back', 'Bodyweight', 'beginner'),
  ('Band Pull-Apart', 'Back', 'Equipment', 'beginner'),
  ('Cable Face Pull Wide', 'Back', 'Cable', 'beginner'),
  ('Landmine Row', 'Back', 'Barbell', 'intermediate'),
  ('Gorilla Row', 'Back', 'Kettlebell', 'intermediate'),
  ('Renegade Row', 'Back', 'Dumbbell', 'advanced'),
  ('Helms Row', 'Back', 'Dumbbell', 'intermediate'),
  ('Cable Rope Pullover', 'Back', 'Cable', 'beginner'),
  ('Iso-Lateral Row Machine', 'Back', 'Machine', 'beginner'),
  ('Smith Machine Row', 'Back', 'Machine', 'beginner'),
  ('Front Squat', 'Legs', 'Barbell', 'intermediate'),
  ('Safety Bar Squat', 'Legs', 'Barbell', 'intermediate'),
  ('Box Squat', 'Legs', 'Barbell', 'intermediate'),
  ('Pause Squat', 'Legs', 'Barbell', 'advanced'),
  ('Zercher Squat', 'Legs', 'Barbell', 'advanced'),
  ('Overhead Squat', 'Legs', 'Barbell', 'advanced'),
  ('Split Squat', 'Legs', 'Dumbbell', 'beginner'),
  ('Reverse Lunge', 'Legs', 'Dumbbell', 'beginner'),
  ('Forward Lunge', 'Legs', 'Barbell', 'beginner'),
  ('Lateral Lunge', 'Legs', 'Dumbbell', 'beginner'),
  ('Curtsy Lunge', 'Legs', 'Dumbbell', 'beginner'),
  ('Deficit Reverse Lunge', 'Legs', 'Dumbbell', 'intermediate'),
  ('Walking Barbell Lunge', 'Legs', 'Barbell', 'intermediate'),
  ('Leg Press Narrow Stance', 'Legs', 'Machine', 'beginner'),
  ('Leg Press Wide Stance', 'Legs', 'Machine', 'beginner'),
  ('Single-Leg Press', 'Legs', 'Machine', 'intermediate'),
  ('Seated Leg Curl', 'Legs', 'Machine', 'beginner'),
  ('Lying Leg Curl', 'Legs', 'Machine', 'beginner'),
  ('Standing Leg Curl', 'Legs', 'Machine', 'beginner'),
  ('Single-Leg Extension', 'Legs', 'Machine', 'beginner'),
  ('Seated Calf Raise', 'Legs', 'Machine', 'beginner'),
  ('Standing Calf Raise', 'Legs', 'Machine', 'beginner'),
  ('Donkey Calf Raise', 'Legs', 'Machine', 'intermediate'),
  ('Single-Leg Calf Raise', 'Legs', 'Bodyweight', 'beginner'),
  ('Smith Machine Squat', 'Legs', 'Machine', 'beginner'),
  ('Belt Squat', 'Legs', 'Machine', 'intermediate'),
  ('Pendulum Squat', 'Legs', 'Machine', 'intermediate'),
  ('V-Squat', 'Legs', 'Machine', 'intermediate'),
  ('Dumbbell RDL', 'Legs', 'Dumbbell', 'beginner'),
  ('Single-Leg RDL', 'Legs', 'Dumbbell', 'intermediate'),
  ('Stiff-Leg Deadlift', 'Legs', 'Barbell', 'intermediate'),
  ('Cable Pull-Through', 'Legs', 'Cable', 'beginner'),
  ('Barbell Hip Thrust', 'Legs', 'Barbell', 'intermediate'),
  ('Single-Leg Hip Thrust', 'Legs', 'Bodyweight', 'intermediate'),
  ('Frog Pump', 'Legs', 'Bodyweight', 'beginner'),
  ('Cable Kickback', 'Legs', 'Cable', 'beginner'),
  ('Machine Hip Abduction', 'Legs', 'Machine', 'beginner'),
  ('Machine Hip Adduction', 'Legs', 'Machine', 'beginner'),
  ('Banded Lateral Walk', 'Legs', 'Equipment', 'beginner'),
  ('Clamshell', 'Legs', 'Bodyweight', 'beginner'),
  ('Wall Sit', 'Legs', 'Bodyweight', 'beginner'),
  ('Pistol Squat', 'Legs', 'Bodyweight', 'advanced'),
  ('Shrimp Squat', 'Legs', 'Bodyweight', 'advanced'),
  ('Sissy Squat', 'Legs', 'Bodyweight', 'advanced'),
  ('Cossack Squat', 'Legs', 'Bodyweight', 'intermediate'),
  ('Jefferson Squat', 'Legs', 'Barbell', 'advanced'),
  ('Anderson Squat', 'Legs', 'Barbell', 'advanced'),
  ('Pin Squat', 'Legs', 'Barbell', 'advanced'),
  ('Dumbbell Step-Up', 'Legs', 'Dumbbell', 'beginner'),
  ('Lateral Step-Up', 'Legs', 'Dumbbell', 'beginner'),
  ('Box Step-Down', 'Legs', 'Bodyweight', 'beginner'),
  ('Spanish Squat', 'Legs', 'Equipment', 'beginner'),
  ('Heel-Elevated Goblet Squat', 'Legs', 'Dumbbell', 'beginner'),
  ('Sumo Goblet Squat', 'Legs', 'Dumbbell', 'beginner'),
  ('Landmine Squat', 'Legs', 'Barbell', 'beginner'),
  ('Cyclist Squat', 'Legs', 'Dumbbell', 'intermediate'),
  ('Seated Barbell Overhead Press', 'Shoulders', 'Barbell', 'intermediate'),
  ('Push Press', 'Shoulders', 'Barbell', 'intermediate'),
  ('Z Press', 'Shoulders', 'Barbell', 'advanced'),
  ('Landmine Shoulder Press', 'Shoulders', 'Barbell', 'beginner'),
  ('Single-Arm Dumbbell Press', 'Shoulders', 'Dumbbell', 'beginner'),
  ('Machine Shoulder Press', 'Shoulders', 'Machine', 'beginner'),
  ('Cable Lateral Raise', 'Shoulders', 'Cable', 'beginner'),
  ('Leaning Lateral Raise', 'Shoulders', 'Dumbbell', 'intermediate'),
  ('Seated Lateral Raise', 'Shoulders', 'Dumbbell', 'beginner'),
  ('Cable Front Raise', 'Shoulders', 'Cable', 'beginner'),
  ('Plate Front Raise', 'Shoulders', 'Equipment', 'beginner'),
  ('Bent-Over Lateral Raise', 'Shoulders', 'Dumbbell', 'beginner'),
  ('Cable Reverse Fly', 'Shoulders', 'Cable', 'beginner'),
  ('Machine Reverse Fly', 'Shoulders', 'Machine', 'beginner'),
  ('Barbell Shrug', 'Shoulders', 'Barbell', 'beginner'),
  ('Cable Shrug', 'Shoulders', 'Cable', 'beginner'),
  ('Behind-the-Neck Press', 'Shoulders', 'Barbell', 'advanced'),
  ('Cuban Press', 'Shoulders', 'Dumbbell', 'intermediate'),
  ('Scott Press', 'Shoulders', 'Dumbbell', 'intermediate'),
  ('Y Raise', 'Shoulders', 'Dumbbell', 'beginner'),
  ('T Raise', 'Shoulders', 'Dumbbell', 'beginner'),
  ('W Raise', 'Shoulders', 'Dumbbell', 'beginner'),
  ('Prone Y Raise', 'Shoulders', 'Dumbbell', 'beginner'),
  ('Cable Y Raise', 'Shoulders', 'Cable', 'beginner'),
  ('High Pull', 'Shoulders', 'Barbell', 'intermediate'),
  ('Dumbbell High Pull', 'Shoulders', 'Dumbbell', 'intermediate'),
  ('Bradford Press', 'Shoulders', 'Barbell', 'advanced'),
  ('Bottoms-Up Kettlebell Press', 'Shoulders', 'Kettlebell', 'advanced'),
  ('Half-Kneeling Landmine Press', 'Shoulders', 'Barbell', 'beginner'),
  ('Scapular Pull-Up', 'Shoulders', 'Bodyweight', 'beginner'),
  ('Wall Angel', 'Shoulders', 'Bodyweight', 'beginner'),
  ('Band External Rotation', 'Shoulders', 'Equipment', 'beginner'),
  ('Cable External Rotation', 'Shoulders', 'Cable', 'beginner'),
  ('Incline Dumbbell Curl', 'Arms', 'Dumbbell', 'beginner'),
  ('Spider Curl', 'Arms', 'Dumbbell', 'intermediate'),
  ('Cable Curl', 'Arms', 'Cable', 'beginner'),
  ('EZ-Bar Curl', 'Arms', 'Barbell', 'beginner'),
  ('Drag Curl', 'Arms', 'Barbell', 'intermediate'),
  ('Zottman Curl', 'Arms', 'Dumbbell', 'intermediate'),
  ('Cross-Body Hammer Curl', 'Arms', 'Dumbbell', 'beginner'),
  ('Bayesian Curl', 'Arms', 'Cable', 'intermediate'),
  ('Machine Preacher Curl', 'Arms', 'Machine', 'beginner'),
  ('21s Curl', 'Arms', 'Barbell', 'intermediate'),
  ('Reverse Curl', 'Arms', 'Barbell', 'beginner'),
  ('Wrist Curl', 'Arms', 'Dumbbell', 'beginner'),
  ('Reverse Wrist Curl', 'Arms', 'Dumbbell', 'beginner'),
  ('Farmer Hold', 'Arms', 'Dumbbell', 'beginner'),
  ('JM Press', 'Arms', 'Barbell', 'advanced'),
  ('Dumbbell Skull Crusher', 'Arms', 'Dumbbell', 'beginner'),
  ('Cable Overhead Tricep Extension', 'Arms', 'Cable', 'beginner'),
  ('Single-Arm Tricep Pushdown', 'Arms', 'Cable', 'beginner'),
  ('Kickback', 'Arms', 'Dumbbell', 'beginner'),
  ('Bench Dip', 'Arms', 'Bodyweight', 'beginner'),
  ('Diamond Push-Up Triceps', 'Arms', 'Bodyweight', 'intermediate'),
  ('Tate Press', 'Arms', 'Dumbbell', 'intermediate'),
  ('French Press', 'Arms', 'Barbell', 'intermediate'),
  ('V-Bar Pushdown', 'Arms', 'Cable', 'beginner'),
  ('Straight-Bar Pushdown', 'Arms', 'Cable', 'beginner'),
  ('Machine Tricep Extension', 'Arms', 'Machine', 'beginner'),
  ('Close-Grip Push-Up', 'Arms', 'Bodyweight', 'beginner'),
  ('Band Curl', 'Arms', 'Equipment', 'beginner'),
  ('Band Tricep Pushdown', 'Arms', 'Equipment', 'beginner'),
  ('Hollow Body Hold', 'Core', 'Bodyweight', 'intermediate'),
  ('Hollow Rock', 'Core', 'Bodyweight', 'intermediate'),
  ('V-Up', 'Core', 'Bodyweight', 'intermediate'),
  ('Sit-Up', 'Core', 'Bodyweight', 'beginner'),
  ('Bicycle Crunch', 'Core', 'Bodyweight', 'beginner'),
  ('Reverse Crunch', 'Core', 'Bodyweight', 'beginner'),
  ('Toe Touch Crunch', 'Core', 'Bodyweight', 'beginner'),
  ('Cable Crunch', 'Core', 'Cable', 'beginner'),
  ('Machine Crunch', 'Core', 'Machine', 'beginner'),
  ('Hanging Knee Raise', 'Core', 'Bodyweight', 'beginner'),
  ('Toes-to-Bar', 'Core', 'Bodyweight', 'advanced'),
  ('Captain Chair Leg Raise', 'Core', 'Machine', 'beginner'),
  ('Flutter Kick', 'Core', 'Bodyweight', 'beginner'),
  ('Scissor Kick', 'Core', 'Bodyweight', 'beginner'),
  ('Jackknife', 'Core', 'Bodyweight', 'intermediate'),
  ('Dragon Flag', 'Core', 'Bodyweight', 'advanced'),
  ('L-Sit', 'Core', 'Bodyweight', 'advanced'),
  ('Tuck Planche Hold', 'Core', 'Bodyweight', 'advanced'),
  ('Copenhagen Plank', 'Core', 'Bodyweight', 'advanced'),
  ('RKC Plank', 'Core', 'Bodyweight', 'intermediate'),
  ('Long-Lever Plank', 'Core', 'Bodyweight', 'intermediate'),
  ('Stir the Pot', 'Core', 'Equipment', 'advanced'),
  ('Stability Ball Crunch', 'Core', 'Equipment', 'beginner'),
  ('Stability Ball Pike', 'Core', 'Equipment', 'intermediate'),
  ('Stability Ball Rollout', 'Core', 'Equipment', 'intermediate'),
  ('Medicine Ball Russian Twist', 'Core', 'Equipment', 'beginner'),
  ('Cable Anti-Rotation Press', 'Core', 'Cable', 'beginner'),
  ('Half-Kneeling Pallof Press', 'Core', 'Cable', 'beginner'),
  ('Standing Cable Woodchop', 'Core', 'Cable', 'intermediate'),
  ('Kneeling Cable Woodchop', 'Core', 'Cable', 'beginner'),
  ('Landmine Rotation', 'Core', 'Barbell', 'intermediate'),
  ('Suitcase Carry', 'Core', 'Dumbbell', 'beginner'),
  ('Overhead Carry', 'Core', 'Dumbbell', 'intermediate'),
  ('Dead Bug with Band', 'Core', 'Equipment', 'beginner'),
  ('McGill Curl-Up', 'Core', 'Bodyweight', 'beginner'),
  ('Side Bend', 'Core', 'Dumbbell', 'beginner'),
  ('Cable Side Bend', 'Core', 'Cable', 'beginner'),
  ('Elliptical', 'Cardio', 'Machine', 'beginner'),
  ('SkiErg', 'Cardio', 'Machine', 'beginner'),
  ('Air Bike Interval', 'Cardio', 'Machine', 'intermediate'),
  ('Treadmill Incline Walk', 'Cardio', 'Machine', 'beginner'),
  ('Treadmill Sprint Interval', 'Cardio', 'Machine', 'intermediate'),
  ('Jumping Jack', 'Cardio', 'Bodyweight', 'beginner'),
  ('High Knees', 'Cardio', 'Bodyweight', 'beginner'),
  ('Butt Kick', 'Cardio', 'Bodyweight', 'beginner'),
  ('Skater Hop', 'Cardio', 'Bodyweight', 'intermediate'),
  ('Broad Jump', 'Full Body', 'Bodyweight', 'intermediate'),
  ('Tuck Jump', 'Full Body', 'Bodyweight', 'intermediate'),
  ('Depth Jump', 'Full Body', 'Equipment', 'advanced'),
  ('Sled Drag', 'Full Body', 'Equipment', 'intermediate'),
  ('Sled Pull', 'Full Body', 'Equipment', 'intermediate'),
  ('Prowler Push', 'Full Body', 'Equipment', 'intermediate'),
  ('Tire Flip', 'Full Body', 'Equipment', 'advanced'),
  ('Sandbag Clean', 'Full Body', 'Equipment', 'intermediate'),
  ('Sandbag Carry', 'Full Body', 'Equipment', 'beginner'),
  ('Kettlebell Clean', 'Full Body', 'Kettlebell', 'intermediate'),
  ('Kettlebell Snatch', 'Full Body', 'Kettlebell', 'advanced'),
  ('Kettlebell Clean and Press', 'Full Body', 'Kettlebell', 'intermediate'),
  ('Kettlebell Goblet Carry', 'Full Body', 'Kettlebell', 'beginner'),
  ('Dumbbell Thruster', 'Full Body', 'Dumbbell', 'intermediate'),
  ('Barbell Thruster', 'Full Body', 'Barbell', 'intermediate'),
  ('Dumbbell Clean', 'Full Body', 'Dumbbell', 'intermediate'),
  ('Dumbbell Snatch', 'Full Body', 'Dumbbell', 'advanced'),
  ('Power Clean', 'Full Body', 'Barbell', 'advanced'),
  ('Hang Clean', 'Full Body', 'Barbell', 'advanced'),
  ('Power Snatch', 'Full Body', 'Barbell', 'advanced'),
  ('Push Jerk', 'Full Body', 'Barbell', 'advanced'),
  ('Split Jerk', 'Full Body', 'Barbell', 'advanced'),
  ('Medicine Ball Chest Pass', 'Full Body', 'Equipment', 'beginner'),
  ('Medicine Ball Rotational Throw', 'Full Body', 'Equipment', 'intermediate'),
  ('Wall Ball', 'Full Body', 'Equipment', 'intermediate'),
  ('Devil Press', 'Full Body', 'Dumbbell', 'advanced'),
  ('Man Maker', 'Full Body', 'Dumbbell', 'advanced'),
  ('Turkish Get-Up', 'Full Body', 'Kettlebell', 'advanced'),
  ('Bear Crawl', 'Full Body', 'Bodyweight', 'beginner'),
  ('Crab Walk', 'Full Body', 'Bodyweight', 'beginner'),
  ('Inchworm', 'Full Body', 'Bodyweight', 'beginner'),
  ('Sprawl', 'Full Body', 'Bodyweight', 'intermediate'),
  ('Burpee Broad Jump', 'Full Body', 'Bodyweight', 'advanced'),
  ('Jumping Lunge', 'Full Body', 'Bodyweight', 'intermediate'),
  ('Kettlebell Complex', 'Full Body', 'Kettlebell', 'advanced'),
  ('Dumbbell Complex', 'Full Body', 'Dumbbell', 'advanced'),
  ('Battle Rope Waves', 'Full Body', 'Equipment', 'beginner'),
  ('Battle Rope Slams', 'Full Body', 'Equipment', 'intermediate'),
  ('Double-Under', 'Cardio', 'Equipment', 'advanced'),
  ('Single-Under', 'Cardio', 'Equipment', 'beginner'),
  ('Shadow Boxing', 'Cardio', 'Bodyweight', 'beginner'),
  ('Heavy Bag Punch', 'Cardio', 'Equipment', 'beginner'),
  ('Rowing Interval', 'Cardio', 'Machine', 'intermediate'),
  ('Swimming', 'Cardio', 'Bodyweight', 'beginner'),
  ('Outdoor Run', 'Cardio', 'Bodyweight', 'beginner'),
  ('Hill Sprint', 'Cardio', 'Bodyweight', 'intermediate'),
  ('Bike Outdoor', 'Cardio', 'Machine', 'beginner'),
  ('Ruck March', 'Cardio', 'Equipment', 'beginner'),
  ('Loaded Carry Mixed', 'Full Body', 'Dumbbell', 'intermediate'),
  ('Yoke Walk', 'Full Body', 'Equipment', 'advanced'),
  ('Atlas Stone Lift', 'Full Body', 'Equipment', 'advanced'),
  ('Log Press', 'Full Body', 'Equipment', 'advanced'),
  ('Axle Deadlift', 'Full Body', 'Barbell', 'advanced')
) AS seed(name, muscle_group, equipment, difficulty)
WHERE NOT EXISTS (
  SELECT 1 FROM exercises e WHERE e.name = seed.name
);
