-- ============================================
-- EXERCISE VIDEO URLS — expansion (CA-102)
-- Curated YouTube demos (family-matched where exact clip shared)
-- Safe to re-run — overwrites by exact name.
-- ============================================

UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=8iPEnn-ltC8' WHERE name = 'Dumbbell Bench Press';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=vcBig73ojpE' WHERE name = 'Incline Barbell Bench Press';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=LfyQJYLKvQQ' WHERE name = 'Decline Dumbbell Press';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=vcBig73ojpE' WHERE name = 'Floor Press';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=8iPEnn-ltC8' WHERE name = 'Dumbbell Floor Press';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=vcBig73ojpE' WHERE name = 'Machine Chest Press';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=vcBig73ojpE' WHERE name = 'Smith Machine Bench Press';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=eozdVDA78K0' WHERE name = 'Incline Cable Fly';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=eozdVDA78K0' WHERE name = 'Decline Cable Fly';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=eGyd5t6t_kE' WHERE name = 'Pec Deck Fly';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=eozdVDA78K0' WHERE name = 'Svend Press';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=vcBig73ojpE' WHERE name = 'Landmine Press';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=taI4XduLpTk' WHERE name = 'Single-Arm Cable Chest Press';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=IODxDxX7oi4' WHERE name = 'Push-Up Wide Grip';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=IODxDxX7oi4' WHERE name = 'Diamond Push-Up';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=IODxDxX7oi4' WHERE name = 'Decline Push-Up';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=IODxDxX7oi4' WHERE name = 'Incline Push-Up';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=IODxDxX7oi4' WHERE name = 'Archer Push-Up';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=IODxDxX7oi4' WHERE name = 'Plyo Push-Up';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=2z8JmcrW-As' WHERE name = 'Chest Dip';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=IODxDxX7oi4' WHERE name = 'Ring Push-Up';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=vcBig73ojpE' WHERE name = 'Guillotine Press';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=8iPEnn-ltC8' WHERE name = 'Neutral-Grip Dumbbell Press';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=taI4XduLpTk' WHERE name = 'Low Cable Crossover';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=taI4XduLpTk' WHERE name = 'High Cable Crossover';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=8iPEnn-ltC8' WHERE name = 'Machine Incline Press';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=vcBig73ojpE' WHERE name = 'Paused Bench Press';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=vcBig73ojpE' WHERE name = 'Spoto Press';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=vcBig73ojpE' WHERE name = 'Board Press';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=8iPEnn-ltC8' WHERE name = 'Hex Press';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=sIvJTfGxdFo' WHERE name = 'Chin-Up';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=sIvJTfGxdFo' WHERE name = 'Neutral-Grip Pull-Up';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=sIvJTfGxdFo' WHERE name = 'Assisted Pull-Up';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=pYcpY20QaE8' WHERE name = 'Chest-Supported Row';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=kBWAon7ItNs' WHERE name = 'Pendlay Row';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=kBWAon7ItNs' WHERE name = 'Yates Row';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=j3Igk5nyZE4' WHERE name = 'Meadows Row';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=1uDTTyZwZQY' WHERE name = 'Cable Straight-Arm Pullover';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=1uDTTyZwZQY' WHERE name = 'Dumbbell Pullover';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=GZbfZ033f74' WHERE name = 'Machine Row';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=sIvJTfGxdFo' WHERE name = 'Inverted Row';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=sIvJTfGxdFo' WHERE name = 'Ring Row';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=kBWAon7ItNs' WHERE name = 'Seal Row';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=pYcpY20QaE8' WHERE name = 'Kroc Row';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=CAwf7n6Luuc' WHERE name = 'Wide-Grip Lat Pulldown';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=CAwf7n6Luuc' WHERE name = 'Close-Grip Lat Pulldown';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=CAwf7n6Luuc' WHERE name = 'Single-Arm Lat Pulldown';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=pYcpY20QaE8' WHERE name = 'Face-Down Incline Row';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=ZaTM37cfiDs' WHERE name = 'Rack Pull';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=ZaTM37cfiDs' WHERE name = 'Sumo Deadlift';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=ZaTM37cfiDs' WHERE name = 'Trap Bar Deadlift';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=ZaTM37cfiDs' WHERE name = 'Snatch-Grip Deadlift';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=ZaTM37cfiDs' WHERE name = 'Deficit Deadlift';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=_oyxCn2iSjU' WHERE name = 'Good Morning';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=_oyxCn2iSjU' WHERE name = 'Hyperextension';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=_oyxCn2iSjU' WHERE name = 'Reverse Hyperextension';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=ASdvN_XEl_c' WHERE name = 'Superman Hold';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=g_tc_HQYPzk' WHERE name = 'Bird Dog';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=ljgqer1ZpXg' WHERE name = 'Band Pull-Apart';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=ljgqer1ZpXg' WHERE name = 'Cable Face Pull Wide';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=j3Igk5nyZE4' WHERE name = 'Landmine Row';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=pYcpY20QaE8' WHERE name = 'Gorilla Row';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=pYcpY20QaE8' WHERE name = 'Renegade Row';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=pYcpY20QaE8' WHERE name = 'Helms Row';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=1uDTTyZwZQY' WHERE name = 'Cable Rope Pullover';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=GZbfZ033f74' WHERE name = 'Iso-Lateral Row Machine';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=kBWAon7ItNs' WHERE name = 'Smith Machine Row';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=bEv6CCg2BC8' WHERE name = 'Front Squat';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=bEv6CCg2BC8' WHERE name = 'Safety Bar Squat';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=bEv6CCg2BC8' WHERE name = 'Box Squat';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=bEv6CCg2BC8' WHERE name = 'Pause Squat';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=bEv6CCg2BC8' WHERE name = 'Zercher Squat';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=bEv6CCg2BC8' WHERE name = 'Overhead Squat';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=2C-uNgKwPLE' WHERE name = 'Split Squat';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=L1i7M0LvFL8' WHERE name = 'Reverse Lunge';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=L1i7M0LvFL8' WHERE name = 'Forward Lunge';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=L1i7M0LvFL8' WHERE name = 'Lateral Lunge';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=L1i7M0LvFL8' WHERE name = 'Curtsy Lunge';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=L1i7M0LvFL8' WHERE name = 'Deficit Reverse Lunge';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=L1i7M0LvFL8' WHERE name = 'Walking Barbell Lunge';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=IZit57r0MUY' WHERE name = 'Leg Press Narrow Stance';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=IZit57r0MUY' WHERE name = 'Leg Press Wide Stance';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=IZit57r0MUY' WHERE name = 'Single-Leg Press';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=1Tq3QdYUuHs' WHERE name = 'Seated Leg Curl';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=1Tq3QdYUuHs' WHERE name = 'Lying Leg Curl';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=1Tq3QdYUuHs' WHERE name = 'Standing Leg Curl';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=YyvSfVtQowg' WHERE name = 'Single-Leg Extension';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=gwLzBJYoWlo' WHERE name = 'Seated Calf Raise';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=gwLzBJYoWlo' WHERE name = 'Standing Calf Raise';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=gwLzBJYoWlo' WHERE name = 'Donkey Calf Raise';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=gwLzBJYoWlo' WHERE name = 'Single-Leg Calf Raise';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=bEv6CCg2BC8' WHERE name = 'Smith Machine Squat';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=bEv6CCg2BC8' WHERE name = 'Belt Squat';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=EdtaJR3X_0I' WHERE name = 'Pendulum Squat';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=EdtaJR3X_0I' WHERE name = 'V-Squat';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=_oyxCn2iSjU' WHERE name = 'Dumbbell RDL';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=_oyxCn2iSjU' WHERE name = 'Single-Leg RDL';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=_oyxCn2iSjU' WHERE name = 'Stiff-Leg Deadlift';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=LM8XHLYJoYs' WHERE name = 'Cable Pull-Through';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=LM8XHLYJoYs' WHERE name = 'Barbell Hip Thrust';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=LM8XHLYJoYs' WHERE name = 'Single-Leg Hip Thrust';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=OUgsJNzsZhI' WHERE name = 'Frog Pump';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=OUgsJNzsZhI' WHERE name = 'Cable Kickback';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=OUgsJNzsZhI' WHERE name = 'Machine Hip Abduction';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=OUgsJNzsZhI' WHERE name = 'Machine Hip Adduction';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=OUgsJNzsZhI' WHERE name = 'Banded Lateral Walk';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=OUgsJNzsZhI' WHERE name = 'Clamshell';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=bEv6CCg2BC8' WHERE name = 'Wall Sit';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=bEv6CCg2BC8' WHERE name = 'Pistol Squat';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=bEv6CCg2BC8' WHERE name = 'Shrimp Squat';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=bEv6CCg2BC8' WHERE name = 'Sissy Squat';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=bEv6CCg2BC8' WHERE name = 'Cossack Squat';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=bEv6CCg2BC8' WHERE name = 'Jefferson Squat';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=bEv6CCg2BC8' WHERE name = 'Anderson Squat';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=bEv6CCg2BC8' WHERE name = 'Pin Squat';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=dQqApCGd5Ss' WHERE name = 'Dumbbell Step-Up';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=dQqApCGd5Ss' WHERE name = 'Lateral Step-Up';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=dQqApCGd5Ss' WHERE name = 'Box Step-Down';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=bEv6CCg2BC8' WHERE name = 'Spanish Squat';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=MeIiIdrhGWo' WHERE name = 'Heel-Elevated Goblet Squat';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=MeIiIdrhGWo' WHERE name = 'Sumo Goblet Squat';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=MeIiIdrhGWo' WHERE name = 'Landmine Squat';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=MeIiIdrhGWo' WHERE name = 'Cyclist Squat';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=2yjwXTZQDDI' WHERE name = 'Seated Barbell Overhead Press';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=2yjwXTZQDDI' WHERE name = 'Push Press';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=2yjwXTZQDDI' WHERE name = 'Z Press';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=qEwKCR5JCog' WHERE name = 'Landmine Shoulder Press';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=qEwKCR5JCog' WHERE name = 'Single-Arm Dumbbell Press';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=qEwKCR5JCog' WHERE name = 'Machine Shoulder Press';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=3VcKaXpzqRo' WHERE name = 'Cable Lateral Raise';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=3VcKaXpzqRo' WHERE name = 'Leaning Lateral Raise';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=3VcKaXpzqRo' WHERE name = 'Seated Lateral Raise';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=-t7fuZ0KhDA' WHERE name = 'Cable Front Raise';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=-t7fuZ0KhDA' WHERE name = 'Plate Front Raise';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=JoCRRZ3zRtI' WHERE name = 'Bent-Over Lateral Raise';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=JoCRRZ3zRtI' WHERE name = 'Cable Reverse Fly';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=JoCRRZ3zRtI' WHERE name = 'Machine Reverse Fly';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=cJRVVxmytaM' WHERE name = 'Barbell Shrug';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=cJRVVxmytaM' WHERE name = 'Cable Shrug';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=2yjwXTZQDDI' WHERE name = 'Behind-the-Neck Press';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=6Z15_WdXmVw' WHERE name = 'Cuban Press';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=6Z15_WdXmVw' WHERE name = 'Scott Press';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=JoCRRZ3zRtI' WHERE name = 'Y Raise';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=JoCRRZ3zRtI' WHERE name = 'T Raise';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=ljgqer1ZpXg' WHERE name = 'W Raise';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=JoCRRZ3zRtI' WHERE name = 'Prone Y Raise';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=ljgqer1ZpXg' WHERE name = 'Cable Y Raise';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=amCVPlM_eXc' WHERE name = 'High Pull';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=amCVPlM_eXc' WHERE name = 'Dumbbell High Pull';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=2yjwXTZQDDI' WHERE name = 'Bradford Press';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=qEwKCR5JCog' WHERE name = 'Bottoms-Up Kettlebell Press';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=qEwKCR5JCog' WHERE name = 'Half-Kneeling Landmine Press';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=sIvJTfGxdFo' WHERE name = 'Scapular Pull-Up';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=ljgqer1ZpXg' WHERE name = 'Wall Angel';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=ljgqer1ZpXg' WHERE name = 'Band External Rotation';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=ljgqer1ZpXg' WHERE name = 'Cable External Rotation';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=ykJmrZ5v0Pk' WHERE name = 'Incline Dumbbell Curl';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=ykJmrZ5v0Pk' WHERE name = 'Spider Curl';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=ykJmrZ5v0Pk' WHERE name = 'Cable Curl';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=kwG2ipFng_U' WHERE name = 'EZ-Bar Curl';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=kwG2ipFng_U' WHERE name = 'Drag Curl';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=zC3xbLpSn2c' WHERE name = 'Zottman Curl';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=zC3xbLpSn2c' WHERE name = 'Cross-Body Hammer Curl';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=ykJmrZ5v0Pk' WHERE name = 'Bayesian Curl';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=fI1ueUBCcy4' WHERE name = 'Machine Preacher Curl';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=kwG2ipFng_U' WHERE name = '21s Curl';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=kwG2ipFng_U' WHERE name = 'Reverse Curl';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=ykJmrZ5v0Pk' WHERE name = 'Wrist Curl';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=ykJmrZ5v0Pk' WHERE name = 'Reverse Wrist Curl';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=p5QbbC1H_bI' WHERE name = 'Farmer Hold';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=nEF0bv2FC9A' WHERE name = 'JM Press';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=d_KZxkY_0cA' WHERE name = 'Dumbbell Skull Crusher';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=YbX7Wd8jQ1g' WHERE name = 'Cable Overhead Tricep Extension';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=2-LAMcpzODU' WHERE name = 'Single-Arm Tricep Pushdown';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=YbX7Wd8jQ1g' WHERE name = 'Kickback';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=2z8JmcrW-As' WHERE name = 'Bench Dip';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=IODxDxX7oi4' WHERE name = 'Diamond Push-Up Triceps';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=d_KZxkY_0cA' WHERE name = 'Tate Press';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=d_KZxkY_0cA' WHERE name = 'French Press';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=2-LAMcpzODU' WHERE name = 'V-Bar Pushdown';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=2-LAMcpzODU' WHERE name = 'Straight-Bar Pushdown';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=YbX7Wd8jQ1g' WHERE name = 'Machine Tricep Extension';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=IODxDxX7oi4' WHERE name = 'Close-Grip Push-Up';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=ykJmrZ5v0Pk' WHERE name = 'Band Curl';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=2-LAMcpzODU' WHERE name = 'Band Tricep Pushdown';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=ASdvN_XEl_c' WHERE name = 'Hollow Body Hold';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=ASdvN_XEl_c' WHERE name = 'Hollow Rock';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=Xyd_fa5zoEU' WHERE name = 'V-Up';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=Xyd_fa5zoEU' WHERE name = 'Sit-Up';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=Xyd_fa5zoEU' WHERE name = 'Bicycle Crunch';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=Xyd_fa5zoEU' WHERE name = 'Reverse Crunch';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=Xyd_fa5zoEU' WHERE name = 'Toe Touch Crunch';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=Xyd_fa5zoEU' WHERE name = 'Cable Crunch';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=Xyd_fa5zoEU' WHERE name = 'Machine Crunch';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=hdng3Nm1z0E' WHERE name = 'Hanging Knee Raise';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=hdng3Nm1z0E' WHERE name = 'Toes-to-Bar';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=hdng3Nm1z0E' WHERE name = 'Captain Chair Leg Raise';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=nmwgirgXLYM' WHERE name = 'Flutter Kick';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=nmwgirgXLYM' WHERE name = 'Scissor Kick';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=Xyd_fa5zoEU' WHERE name = 'Jackknife';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=p47fEXGabaY' WHERE name = 'Dragon Flag';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=ASdvN_XEl_c' WHERE name = 'L-Sit';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=ASdvN_XEl_c' WHERE name = 'Tuck Planche Hold';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=K2VljzCC16g' WHERE name = 'Copenhagen Plank';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=ASdvN_XEl_c' WHERE name = 'RKC Plank';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=ASdvN_XEl_c' WHERE name = 'Long-Lever Plank';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=ASdvN_XEl_c' WHERE name = 'Stir the Pot';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=Xyd_fa5zoEU' WHERE name = 'Stability Ball Crunch';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=p47fEXGabaY' WHERE name = 'Stability Ball Pike';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=p47fEXGabaY' WHERE name = 'Stability Ball Rollout';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=wkD8rjkodUI' WHERE name = 'Medicine Ball Russian Twist';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=AH_QZLm_0-s' WHERE name = 'Cable Anti-Rotation Press';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=AH_QZLm_0-s' WHERE name = 'Half-Kneeling Pallof Press';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=pAplQXk3dkU' WHERE name = 'Standing Cable Woodchop';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=pAplQXk3dkU' WHERE name = 'Kneeling Cable Woodchop';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=pAplQXk3dkU' WHERE name = 'Landmine Rotation';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=p5QbbC1H_bI' WHERE name = 'Suitcase Carry';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=p5QbbC1H_bI' WHERE name = 'Overhead Carry';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=g_tc_HQYPzk' WHERE name = 'Dead Bug with Band';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=Xyd_fa5zoEU' WHERE name = 'McGill Curl-Up';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=K2VljzCC16g' WHERE name = 'Side Bend';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=K2VljzCC16g' WHERE name = 'Cable Side Bend';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=brFHyOtTwH4' WHERE name = 'Elliptical';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=zQ82RYIJz9o' WHERE name = 'SkiErg';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=pPJ_o1UqSyc' WHERE name = 'Air Bike Interval';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=brFHyOtTwH4' WHERE name = 'Treadmill Incline Walk';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=brFHyOtTwH4' WHERE name = 'Treadmill Sprint Interval';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=1BZM2Vre5oc' WHERE name = 'Jumping Jack';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=nmwgirgXLYM' WHERE name = 'High Knees';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=nmwgirgXLYM' WHERE name = 'Butt Kick';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=NKR0_z8k_zY' WHERE name = 'Skater Hop';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=NKR0_z8k_zY' WHERE name = 'Broad Jump';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=NKR0_z8k_zY' WHERE name = 'Tuck Jump';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=NKR0_z8k_zY' WHERE name = 'Depth Jump';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=MPs9b_OuW1k' WHERE name = 'Sled Drag';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=MPs9b_OuW1k' WHERE name = 'Sled Pull';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=MPs9b_OuW1k' WHERE name = 'Prowler Push';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=ZaTM37cfiDs' WHERE name = 'Tire Flip';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=mKDZI5p1ZWI' WHERE name = 'Sandbag Clean';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=p5QbbC1H_bI' WHERE name = 'Sandbag Carry';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=mKDZI5p1ZWI' WHERE name = 'Kettlebell Clean';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=mKDZI5p1ZWI' WHERE name = 'Kettlebell Snatch';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=mKDZI5p1ZWI' WHERE name = 'Kettlebell Clean and Press';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=p5QbbC1H_bI' WHERE name = 'Kettlebell Goblet Carry';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=bEv6CCg2BC8' WHERE name = 'Dumbbell Thruster';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=bEv6CCg2BC8' WHERE name = 'Barbell Thruster';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=mKDZI5p1ZWI' WHERE name = 'Dumbbell Clean';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=mKDZI5p1ZWI' WHERE name = 'Dumbbell Snatch';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=ZaTM37cfiDs' WHERE name = 'Power Clean';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=ZaTM37cfiDs' WHERE name = 'Hang Clean';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=ZaTM37cfiDs' WHERE name = 'Power Snatch';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=2yjwXTZQDDI' WHERE name = 'Push Jerk';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=2yjwXTZQDDI' WHERE name = 'Split Jerk';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=TwDSI5JiQ6E' WHERE name = 'Medicine Ball Chest Pass';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=TwDSI5JiQ6E' WHERE name = 'Medicine Ball Rotational Throw';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=TwDSI5JiQ6E' WHERE name = 'Wall Ball';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=TU8QYVW0gDQ' WHERE name = 'Devil Press';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=TU8QYVW0gDQ' WHERE name = 'Man Maker';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=mKDZI5p1ZWI' WHERE name = 'Turkish Get-Up';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=nmwgirgXLYM' WHERE name = 'Bear Crawl';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=nmwgirgXLYM' WHERE name = 'Crab Walk';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=ASdvN_XEl_c' WHERE name = 'Inchworm';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=TU8QYVW0gDQ' WHERE name = 'Sprawl';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=TU8QYVW0gDQ' WHERE name = 'Burpee Broad Jump';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=L1i7M0LvFL8' WHERE name = 'Jumping Lunge';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=mKDZI5p1ZWI' WHERE name = 'Kettlebell Complex';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=p5QbbC1H_bI' WHERE name = 'Dumbbell Complex';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=wJnhbTqU8lU' WHERE name = 'Battle Rope Waves';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=wJnhbTqU8lU' WHERE name = 'Battle Rope Slams';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=1BZM2Vre5oc' WHERE name = 'Double-Under';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=1BZM2Vre5oc' WHERE name = 'Single-Under';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=nmwgirgXLYM' WHERE name = 'Shadow Boxing';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=wJnhbTqU8lU' WHERE name = 'Heavy Bag Punch';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=zQ82RYIJz9o' WHERE name = 'Rowing Interval';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=brFHyOtTwH4' WHERE name = 'Swimming';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=brFHyOtTwH4' WHERE name = 'Outdoor Run';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=brFHyOtTwH4' WHERE name = 'Hill Sprint';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=pPJ_o1UqSyc' WHERE name = 'Bike Outdoor';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=p5QbbC1H_bI' WHERE name = 'Ruck March';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=p5QbbC1H_bI' WHERE name = 'Loaded Carry Mixed';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=p5QbbC1H_bI' WHERE name = 'Yoke Walk';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=ZaTM37cfiDs' WHERE name = 'Atlas Stone Lift';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=2yjwXTZQDDI' WHERE name = 'Log Press';
UPDATE exercises SET video_url = 'https://www.youtube.com/watch?v=ZaTM37cfiDs' WHERE name = 'Axle Deadlift';
